version: "3"
services:
  simple_xss:
    build: ./docker/php
    volumes:
      - ./web/simple_xss/:/var/www/html
    ports:
      - 3333:80
  eval:
    build: ./docker/php
    volumes:
     - ./web/eval/:/var/www/html
    ports:
     - 3337:80