version: "3"
services:
  simple_xss:
    build: ./docker/php
    volumes:
      - ./web/simple_xss/:/var/www/html
    ports:
      - 3333:80
  eval:
    build: ./docker/php
    volumes:
      - ./web/eval/:/var/www/html
    ports:
      - 3337:80
  gacha:
    image: golang:alpine
    command: /bin/sh -c "cd /go/src/app && go run main.go"
    volumes:
      - ./web/gacha/:/go/src/app
    ports:
      - 3334:3334
  gachaf:
    build: ./docker/php
    volumes:
      - ./web/gachaf/:/var/www/html
    ports:
      - 3335:80